services:
  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    volumes:
      - app_public:/var/www/html/public
    ports:
      - 8080:80
    networks:
      - reminders

  app:
    build:
      context: ./source
      target: app
    env_file:
      - ./source/.env
    working_dir: /var/www/html
    volumes:
      - app_public:/var/www/html/public
      - ./source:/var/www/html
      - /var/www/html/node_modules/
      - /var/www/html/vendor/
    networks:
      - reminders

networks:
  reminders:
    driver: bridge
    name: reminders

volumes:
  app_public:
